/** Generated by scripts/ingest-law-watch.mjs — do not invent values by hand. */
export const LAW_WATCH_META = {
  lastIngest: null as string | null,
  updatedAt: "2026-09-14",
  status: "scaffold" as "scaffold" | "draft" | "merged",
  cadenceDays: 2,
};
