"use client";

import coverageData from "@/data/fr-coverage.json";
import { useAppState } from "@/components/app-state";
import { trackLabel } from "@/lib/branding";
import { t } from "@/lib/i18n";
import { emptyState, updateProfile } from "@/lib/progress/store";
import { TRACKS, type SupportLevel, type Track } from "@/lib/types";

/** Generated by npm run fr:coverage; a few hundred bytes, not the whole store. */
const coverage = coverageData as {
  tracks: Record<string, { questions: number; stems: number; options: number } | undefined>;
};

export default function SettingsPage() {
  const { state, setState } = useAppState();
  const dict = t(state.profile.locale);
  const tracks = state.profile.tracks;

  function toggleTrack(track: Track) {
    const next = tracks.includes(track)
      ? tracks.filter((item) => item !== track)
      : [...tracks, track];
    if (!next.length) return;
    setState(
      updateProfile(state, {
        tracks: next,
        activeTrack: next.includes(state.profile.activeTrack)
          ? state.profile.activeTrack
          : next[0],
      }),
    );
  }

  return (
    <div className="space-y-6">
      <h1 className="font-serif text-3xl text-black">{dict.settings}</h1>

      <section className="card space-y-3">
        <p className="text-sm font-medium text-black">{dict.switchTrack}</p>
        {TRACKS.map((track) => (
          <label key={track} className="flex min-h-11 items-center gap-3 text-black">
            <input
              type="checkbox"
              checked={tracks.includes(track)}
              onChange={() => toggleTrack(track)}
              className="checkbox mt-0"
            />
            {trackLabel(track)}
          </label>
        ))}
      </section>

      <section className="card space-y-3">
        <label className="flex items-start gap-3">
          <input
            type="checkbox"
            checked={state.profile.showTranslations}
            onChange={(event) =>
              setState(updateProfile(state, { showTranslations: event.target.checked }))
            }
            className="checkbox"
          />
          <span>
            <span className="block text-black">{dict.translationsUnder}</span>
            <span className="text-sm text-[#6b6560]">{dict.translationsUnderHint}</span>
          </span>
        </label>
        <div className="space-y-2 border-t border-[#eee6d6] pt-3">
          <p className="text-xs uppercase tracking-[0.14em] text-[#6b6560]">
            {dict.translationCoverage}
          </p>
          {TRACKS.map((track) => {
            const row = coverage.tracks[track];
            if (!row) return null;
            const pct = Math.round((row.stems / Math.max(1, row.questions)) * 100);
            return (
              <div key={track} className="space-y-1">
                <div className="flex items-baseline justify-between gap-3 text-sm">
                  <span className="text-black">{trackLabel(track)}</span>
                  <span className="tabular-nums text-[#6b6560]">
                    {row.stems}/{row.questions} · {pct}%
                  </span>
                </div>
                <div className="h-1.5 overflow-hidden rounded-full bg-[#ece6d8]">
                  <div
                    className="h-full rounded-full bg-[#1d4ed8]"
                    style={{ width: `${pct}%` }}
                  />
                </div>
              </div>
            );
          })}
          <p className="text-xs leading-5 text-[#8a8276]">{dict.translationCoverageNote}</p>
        </div>
      </section>

      <section className="card space-y-3">
        <label className="flex items-start gap-3">
          <input
            type="checkbox"
            checked={state.profile.fragileMode}
            onChange={(event) =>
              setState(updateProfile(state, { fragileMode: event.target.checked }))
            }
            className="checkbox"
          />
          <span>
            <span className="block text-black">{dict.fragileMode}</span>
            <span className="text-sm text-[#6b6560]">{dict.fragileHint}</span>
          </span>
        </label>
        <label className="block space-y-1">
          <span className="text-sm text-[#6b6560]">{dict.supportFade}</span>
          <input
            type="range"
            min={0}
            max={3}
            value={state.profile.supportLevel}
            onChange={(event) =>
              setState(
                updateProfile(state, {
                  supportLevel: Number(event.target.value) as SupportLevel,
                }),
              )
            }
            className="w-full"
          />
          <span className="text-xs text-[#6b6560]">
            {state.profile.supportLevel >= 2 ? dict.supportHigh : dict.supportLow}
          </span>
        </label>
      </section>

      <section className="card space-y-3">
        <p className="font-medium text-black">{dict.tosTitle}</p>
        <p className="text-sm leading-6 text-[#6b6560]">{dict.tos}</p>
        <label className="block space-y-1">
          <span className="text-sm text-[#6b6560]">{dict.yourEmail}</span>
          <input
            type="email"
            value={state.profile.email ?? ""}
            onChange={(event) =>
              setState(updateProfile(state, { email: event.target.value }))
            }
            className="field"
          />
        </label>
      </section>

      {/*
        The licence line and the corpus note used to sit on the tab bar and the
        home screen. They belong here: a paying user reads them once, on the
        screen where they can act on them.
      */}
      <p className="text-xs leading-5 text-[#8a8276]">{dict.tosAccept}</p>
      <p className="text-xs leading-5 text-[#8a8276]">{dict.protectionNote}</p>
      <p className="text-xs leading-5 text-[#8a8276]">{dict.demoNote}</p>

      <button type="button" className="btn-secondary" onClick={() => setState(emptyState())}>
        {dict.resetProgress}
      </button>
    </div>
  );
}
