/** Public Transportstyrelsen / SFS seed for taxiägare (taxitrafiktillstånd). Swedish exam language only. */

export const OWNER_ITEMS = [
  {
    id: "rs-owner-tillstand-plikt",
    topic: "agare",
    trackHint: "owner",
    corpus: "owner-seed",
    type: "qcm",
    source: "SFS 2012:211 2 kap. 1 §",
    freq: "high",
    trap: "Kommunalt tillstånd räcker",
    sv: "Vad krävs för att bedriva taxitrafik enligt taxitrafiklagen? | Alt: A. Ett kommunalt näringstillstånd | Alt: B. Ett taxitrafiktillstånd | Alt: C. Enbart taxiförarlegitimation | Alt: D. Enbart F-skattsedel",
    fr: "Que faut-il pour exercer le taxi selon la loi ?",
    answer: "B",
    note_sv: "Taxitrafik får bedrivas endast av den som har taxitrafiktillstånd. Källa: SFS 2012:211 2 kap. 1 §.",
    note_fr: "Seul le titulaire d'un taxitrafiktillstånd peut exercer. SFS 2012:211, ch. 2, art. 1.",
  },
  {
    id: "rs-owner-provningsmyndighet",
    topic: "agare",
    trackHint: "owner",
    corpus: "owner-seed",
    type: "qcm",
    source: "SFS 2012:238 2 kap. 1 §",
    freq: "high",
    trap: "Trafikverket / länsstyrelsen",
    sv: "Vilken myndighet prövar frågor om taxitrafiktillstånd? | Alt: A. Trafikverket | Alt: B. Länsstyrelsen | Alt: C. Transportstyrelsen | Alt: D. Kommunen",
    fr: "Quelle autorité instruit le permis d'exploiter ?",
    answer: "C",
    note_sv: "Transportstyrelsen är prövningsmyndighet. Källa: SFS 2012:238 2 kap. 1 §.",
    note_fr: "Transportstyrelsen instruit. SFS 2012:238, ch. 2, art. 1.",
  },
  {
    id: "rs-owner-lamplighet",
    topic: "agare",
    trackHint: "owner",
    corpus: "owner-seed",
    type: "qcm",
    source: "SFS 2012:211 2 kap. 5 §",
    freq: "high",
    trap: "Bara ekonomi eller bara körkort",
    sv: "Vilka tre krav ska den som söker taxitrafiktillstånd uppfylla för att bedömas lämplig? | Alt: A. Enbart körkort B och F-skatt | Alt: B. Yrkeskunnande, ekonomiska förhållanden och gott anseende | Alt: C. Enbart yrkeskunnande och lokalkännedom | Alt: D. Kommunalt godkännande, försäkring och taxameter",
    fr: "Quels trois critères d'aptitude ?",
    answer: "B",
    note_sv: "Tillstånd får endast ges till den som med hänsyn till yrkeskunnande, ekonomiska förhållanden och gott anseende bedöms lämplig. Källa: SFS 2012:211 2 kap. 5 §.",
    note_fr: "Compétence professionnelle, situation financière et bonne réputation. SFS 2012:211, ch. 2, art. 5.",
  },
  {
    id: "rs-owner-kapital-100-50",
    topic: "agare",
    trackHint: "owner",
    corpus: "owner-seed",
    type: "qcm",
    source: "SFS 2012:211 2 kap. 9 §",
    freq: "high",
    trap: "50 000 kr för första fordonet",
    sv: "Vilket belopp ska sökanden normalt förfoga över i kapital och reserver, om inte särskilda skäl finns? | Alt: A. 50 000 kronor för första fordonet och 25 000 kronor för varje ytterligare fordon | Alt: B. 100 000 kronor oavsett antal fordon | Alt: C. 100 000 kronor för ett fordon och 50 000 kronor för varje därutöver tillkommande fordon | Alt: D. 250 000 kronor för första fordonet",
    fr: "Quels fonds propres minimaux ?",
    answer: "C",
    note_sv: "Minst 100 000 kr för ett fordon och 50 000 kr för varje ytterligare fordon, om inte särskilda skäl finns. Likviditet och soliditet ska främst beaktas. Källa: SFS 2012:211 2 kap. 9 §.",
    note_fr: "100 000 kr pour le 1er véhicule, 50 000 kr par véhicule suivant. SFS 2012:211, ch. 2, art. 9.",
  },
  {
    id: "rs-owner-fortlopande-ekonomi",
    topic: "agare",
    trackHint: "owner",
    corpus: "owner-seed",
    type: "qcm",
    source: "SFS 2012:211 2 kap. 10 §+transportstyrelsen/tillsyn-for-taxitrafiktillstand",
    freq: "high",
    trap: "Bara vid ansökan",
    sv: "Vad gäller kravet på ekonomiska resurser efter att taxitrafiktillståndet har meddelats? | Alt: A. Kravet prövas bara vid ansökan | Alt: B. Tillståndshavaren ska kunna styrka att kravet fortlöpande är uppfyllt | Alt: C. Kravet upphör efter tre år | Alt: D. Kravet gäller bara aktiebolag",
    fr: "Les ressources financières sont-elles contrôlées ensuite ?",
    answer: "B",
    note_sv: "Den som innehar taxitrafiktillstånd ska kunna styrka att kravet på ekonomiska resurser fortlöpande uppfylls. Transportstyrelsen kan återkalla tillståndet om bolaget inte kan visa detta. Källa: SFS 2012:211 2 kap. 10 §; Transportstyrelsen, Tillsyn av taxitrafiktillstånd.",
    note_fr: "Le titulaire doit pouvoir justifier en continu. SFS 2012:211, ch. 2, art. 10.",
  },
  {
    id: "rs-owner-trafikansvarig-ab",
    topic: "agare",
    trackHint: "owner",
    corpus: "owner-seed",
    type: "qcm",
    source: "SFS 2012:211 2 kap. 3–4 §§",
    freq: "high",
    trap: "Valfri anställd",
    sv: "Vem är trafikansvarig i ett aktiebolag som har taxitrafiktillstånd, om det finns en verkställande direktör? | Alt: A. Valfri anställd förare | Alt: B. Den verkställande direktören | Alt: C. Revisorn | Alt: D. Beställningscentralen",
    fr: "Qui est traficansvarig dans une SA ?",
    answer: "B",
    note_sv: "Hos juridiska personer ska det finnas trafikansvariga. I aktiebolag är det VD, om det finns en sådan, annars den styrelseledamot som bolaget har utsett. Källa: SFS 2012:211 2 kap. 3–4 §§.",
    note_fr: "Le directeur général, sinon un administrateur désigné. SFS 2012:211, ch. 2, art. 3–4.",
  },
  {
    id: "rs-owner-trafikansvarig-hb",
    topic: "agare",
    trackHint: "owner",
    corpus: "owner-seed",
    type: "qcm",
    source: "SFS 2012:211 2 kap. 4 §",
    freq: "medium",
    trap: "Bara en utsedd bolagsman",
    sv: "Vem är trafikansvarig i ett handelsbolag som har taxitrafiktillstånd? | Alt: A. Bara den bolagsman som bolaget utser | Alt: B. Varje bolagsman | Alt: C. Bara revisorn | Alt: D. Kommunen",
    fr: "Qui est traficansvarig dans une société en nom collectif ?",
    answer: "B",
    note_sv: "I kommanditbolag och andra handelsbolag är varje bolagsman trafikansvarig. Kommanditdelägare kan undantas om det finns särskilda skäl. Källa: SFS 2012:211 2 kap. 4 §.",
    note_fr: "Chaque associé. SFS 2012:211, ch. 2, art. 4.",
  },
  {
    id: "rs-owner-yrkeskunnande-amnen",
    topic: "agare",
    trackHint: "owner",
    corpus: "owner-seed",
    type: "qcm",
    source: "SFS 2012:211 2 kap. 8 §",
    freq: "high",
    sv: "Vad ska provet i yrkeskunnande för taxitrafiktillstånd främst avse? | Alt: A. Bara kartläsning och lokalkännedom | Alt: B. Rättsregler, företagsledning och ekonomisk ledning, tekniska normer och driftsförhållanden samt trafiksäkerhet | Alt: C. Bara taxameterns knappar | Alt: D. Bara arbetsmiljö för förare",
    fr: "Que couvre l'épreuve de compétence du titulaire ?",
    answer: "B",
    note_sv: "Provet ska avse de kunskaper en tillståndshavare bör ha i rättsregler, företagsledning och ekonomisk ledning, tekniska normer och driftsförhållanden samt trafiksäkerhet. Källa: SFS 2012:211 2 kap. 8 §.",
    note_fr: "Droit, gestion, normes techniques/exploitation, sécurité routière. SFS 2012:211, ch. 2, art. 8.",
  },
  {
    id: "rs-owner-prov-ts-tv",
    topic: "agare",
    trackHint: "owner",
    corpus: "owner-seed",
    type: "qcm",
    source: "SFS 2012:238 2 kap. 2–3 §§",
    freq: "medium",
    trap: "Kommunen anordnar provet",
    sv: "Vem utformar respektive anordnar det skriftliga provet i yrkeskunnande för taxitrafiktillstånd? | Alt: A. Kommunen utformar och anordnar | Alt: B. Transportstyrelsen utformar, Trafikverket anordnar | Alt: C. Trafikverket utformar, Skatteverket anordnar | Alt: D. Svenska Taxiförbundet utformar och anordnar",
    fr: "Qui conçoit et qui organise l'épreuve ?",
    answer: "B",
    note_sv: "Transportstyrelsen utformar proven. Trafikverket anordnar dem. Källa: SFS 2012:238 2 kap. 2–3 §§.",
    note_fr: "Transportstyrelsen conçoit, Trafikverket organise. SFS 2012:238, ch. 2, art. 2–3.",
  },
  {
    id: "rs-owner-giltighet-tills-vidare",
    topic: "agare",
    trackHint: "owner",
    corpus: "owner-seed",
    type: "qcm",
    source: "SFS 2012:211 2 kap. 14 §",
    freq: "high",
    trap: "Fem år / tio år",
    sv: "Hur länge gäller ett taxitrafiktillstånd normalt? | Alt: A. Fem år | Alt: B. Tio år | Alt: C. Tills vidare, men det får begränsas till viss tid om det finns särskilda skäl | Alt: D. Tills fordonet säljs",
    fr: "Quelle est la durée du permis d'exploiter ?",
    answer: "C",
    note_sv: "Ett taxitrafiktillstånd gäller tills vidare. Om det finns särskilda skäl får det begränsas till en viss tid. Källa: SFS 2012:211 2 kap. 14 §.",
    note_fr: "Valable jusqu'à nouvel ordre, sauf motif particulier. SFS 2012:211, ch. 2, art. 14.",
  },
  {
    id: "rs-owner-dodsfall-6-man",
    topic: "agare",
    trackHint: "owner",
    corpus: "owner-seed",
    type: "qcm",
    source: "SFS 2012:211 2 kap. 15 §",
    freq: "medium",
    trap: "Tillståndet upphör samma dag",
    sv: "Vad händer med taxitrafiktillståndet om tillståndshavaren dör eller försätts i konkurs? | Alt: A. Tillståndet upphör samma dag | Alt: B. Tillståndet övergår på dödsboet eller konkursboet och gäller högst sex månader, om inte längre tid medges | Alt: C. Tillståndet övergår automatiskt på närmaste anhörige utan tidsgräns | Alt: D. Transportstyrelsen måste meddela nytt tillstånd inom 14 dagar",
    fr: "Décès ou faillite : que devient le permis ?",
    answer: "B",
    note_sv: "Tillståndet övergår på dödsboet eller konkursboet och gäller högst sex månader från dödsfallet eller konkursbeslutet, om inte längre tid medges. Källa: SFS 2012:211 2 kap. 15 §.",
    note_fr: "Passe à la succession / masse, 6 mois max. SFS 2012:211, ch. 2, art. 15.",
  },
  {
    id: "rs-owner-forestandare-1-man",
    topic: "agare",
    trackHint: "owner",
    corpus: "owner-seed",
    type: "qcm",
    source: "SFS 2012:211 2 kap. 15 §",
    freq: "medium",
    sv: "Hur snabbt måste en föreståndare anmälas till prövningsmyndigheten efter dödsfall eller konkurs, för att tillståndet inte ska upphöra? | Alt: A. Inom en vecka | Alt: B. Inom en månad | Alt: C. Inom sex månader | Alt: D. Ingen anmälan krävs",
    fr: "Délai pour désigner un föreståndare ?",
    answer: "B",
    note_sv: "Om en föreståndare inte har anmälts inom en månad efter dödsfallet eller konkursbeslutet upphör tillståndet. Föreståndaren ska godkännas enligt lämplighetskraven. Källa: SFS 2012:211 2 kap. 15 §.",
    note_fr: "Un mois, sinon le permis expire. SFS 2012:211, ch. 2, art. 15.",
  },
  {
    id: "rs-owner-gods-huvudsak",
    topic: "agare",
    trackHint: "owner",
    corpus: "owner-seed",
    type: "qcm",
    source: "SFS 2012:211 2 kap. 16 §",
    freq: "low",
    sv: "Får den som har taxitrafiktillstånd även frakta gods med fordonen? | Alt: A. Nej, aldrig | Alt: B. Ja, under förutsättning att persontransporter utgör den huvudsakliga delen av transportverksamheten | Alt: C. Ja, utan begränsning | Alt: D. Bara om kommunen godkänner det",
    fr: "Le titulaire peut-il aussi transporter des marchandises ?",
    answer: "B",
    note_sv: "Ja, med de fordon tillståndet avser, om persontransporter är den huvudsakliga delen. Källa: SFS 2012:211 2 kap. 16 §.",
    note_fr: "Oui si le transport de personnes reste l'activité principale. SFS 2012:211, ch. 2, art. 16.",
  },
  {
    id: "rs-owner-jamforpris-def",
    topic: "agare",
    trackHint: "owner",
    corpus: "owner-seed",
    type: "qcm",
    source: "SFS 2012:211 2 kap. 20 §+transportstyrelsen/prisinformation",
    freq: "high",
    trap: "Valfri sträcka utan moms",
    sv: "Vad är jämförpriset som tillståndshavaren ska använda i prisinformationen? | Alt: A. Priset för en mil utan startavgift | Alt: B. Priset inklusive moms för en 10 kilometer lång transport som varar 15 minuter, inklusive eventuell grundavgift | Alt: C. Medelpriset för alla körningar under ett dygn | Alt: D. Fast pris till närmaste flygplats",
    fr: "Définition du jämförpris pour l'exploitant ?",
    answer: "B",
    note_sv: "Jämförpriset är priset i kronor inklusive mervärdesskatt för en 10 km lång transport som varar 15 minuter, inklusive eventuell grundavgift. Källa: SFS 2012:211 2 kap. 20 §; Transportstyrelsen, Prisinformation för taxiföretag.",
    note_fr: "10 km / 15 min TTC, prise en charge comprise. SFS 2012:211, ch. 2, art. 20.",
  },
  {
    id: "rs-owner-prisuppgift-700",
    topic: "agare",
    trackHint: "owner",
    corpus: "owner-seed",
    type: "qcm",
    source: "SFS 2012:211 2 kap. 20–21 §§+transportstyrelsen/prisinformation",
    freq: "high",
    trap: "Alltid / aldrig vid taxameter",
    sv: "När ska en bindande prisuppgift lämnas till beställaren? | Alt: A. Alltid före varje resa | Alt: B. När jämförpriset överstiger 700 kronor (1,2 procent av prisbasbeloppet, avrundat nedåt till närmaste tiotal kronor); behövs inte vid fast pris | Alt: C. Bara om kunden begär det | Alt: D. Aldrig när taxameter används",
    fr: "Quand donner un prix maximum contraignant ?",
    answer: "B",
    note_sv: "Prisuppgift ska lämnas om jämförpriset överstiger 1,2 procent av prisbasbeloppet, avrundat nedåt till närmaste tiotal kronor. Transportstyrelsen anger tröskeln 700 kronor. Prisuppgiften ska ange högsta pris och lämnas när färden beställs. Källa: SFS 2012:211 2 kap. 20–21 §§; Transportstyrelsen, Prisinformation för taxiföretag.",
    note_fr: "Si le jämförpris dépasse 700 kr (1,2 % du PBB). Pas si prix fixe. SFS 2012:211, ch. 2, art. 20–21.",
  },
  {
    id: "rs-owner-prisuppgift-spara",
    topic: "agare",
    trackHint: "owner",
    corpus: "owner-seed",
    type: "qcm",
    source: "TSFS 2013:41 6 kap. 11–12 §§+transportstyrelsen/prisinformation",
    freq: "high",
    trap: "Bara tills passet är slut",
    sv: "Hur länge ska bevis om lämnade prisuppgifter sparas? | Alt: A. Bara tills körpasset är slut | Alt: B. De senaste två dygnen i fordonet; alla bevis i sex månader hos tillståndshavaren | Alt: C. En vecka hos föraren | Alt: D. Sju år hos Skatteverket",
    fr: "Combien de temps conserver les preuves de prix ?",
    answer: "B",
    note_sv: "Bevis avseende de senaste två dygnen ska finnas i fordonet. Bevis ska sparas på ett beständigt sätt i sex månader. Transportstyrelsen: de senaste två dygnen i bilen och sex månader hos tillståndshavaren. Källa: TSFS 2013:41 6 kap. 11–12 §§; Transportstyrelsen, Prisinformation för taxiföretag.",
    note_fr: "2 jours dans le véhicule, 6 mois chez l'exploitant. TSFS 2013:41, ch. 6, art. 11–12.",
  },
  {
    id: "rs-owner-prisdekal-inne-ute",
    topic: "agare",
    trackHint: "owner",
    corpus: "owner-seed",
    type: "qcm",
    source: "TSFS 2013:41 6 kap. 1–2, 7–8 §§+transportstyrelsen/prisinformation",
    freq: "high",
    trap: "Bara i vindrutan",
    sv: "Var ska prisinformationen finnas på ett taxifordon med taxameter? | Alt: A. Bara i nedre vänstra hörnet av vindrutan | Alt: B. Väl synlig inne i fordonet och på fordonets utsida (höger och vänster sida), varaktigt utförd enligt TSFS 2013:41 | Alt: C. Bara i förarens pärm | Alt: D. Bara på företagets webbplats",
    fr: "Où afficher les tarifs ?",
    answer: "B",
    note_sv: "Samtliga taxifordon ska ha prisdekaler både inne i och utanpå fordonet. Inne: läsbar från varje passagerarplats. Ute: höger och vänster sida. Mallar i TSFS 2013:41. Källa: TSFS 2013:41 6 kap. 1–2 och 7–8 §§; Transportstyrelsen, Prisinformation för taxiföretag.",
    note_fr: "Intérieur et extérieur, durable, selon TSFS 2013:41.",
  },
  {
    id: "rs-owner-taxa-ej-andra",
    topic: "agare",
    trackHint: "owner",
    corpus: "owner-seed",
    type: "qcm",
    source: "SFS 2012:211 2 kap. 18 §",
    freq: "medium",
    sv: "Vad gäller för hur taxan ska vara uppbyggd? | Alt: A. Taxan får höjas fritt mitt under färden | Alt: B. Priset ska kunna bedömas före färden och beräknas efter körd sträcka och nyttjad tid; grunderna får inte ändras under färden | Alt: C. Bara startavgift behöver anges | Alt: D. Taxan bestäms av kommunen",
    fr: "Comment construire le tarif ?",
    answer: "B",
    note_sv: "Taxan ska vara uppbyggd så att priset enkelt kan bedömas före färden och beräknas efter sträcka och tid. Grunderna för prisets bestämmande får inte förändras under färden. Källa: SFS 2012:211 2 kap. 18 §.",
    note_fr: "Prix estimable avant, calculable après ; bases inchangées pendant la course. SFS 2012:211, ch. 2, art. 18.",
  },
  {
    id: "rs-owner-redovisning-vecka",
    topic: "agare",
    trackHint: "owner",
    corpus: "owner-seed",
    type: "qcm",
    source: "SFS 2012:211 2 a kap. 4 §+transportstyrelsen/redovisningscentraler-for-taxi",
    freq: "high",
    trap: "En gång per år / bara vid kontroll",
    sv: "Hur ofta ska tillståndshavaren överföra taxameteruppgifter till en redovisningscentral? | Alt: A. En gång per år | Alt: B. Minst en gång per vecka | Alt: C. Endast när Transportstyrelsen begär det | Alt: D. Aldrig om fast pris används",
    fr: "Fréquence d'envoi au redovisningscentral ?",
    answer: "B",
    note_sv: "Tillståndshavaren ska överföra taxameteruppgifter från alla anmälda fordon minst en gång per vecka, i obruten följd. Upprepad underlåtenhet kan leda till återkallelse. Källa: SFS 2012:211 2 a kap. 4 § och 4 kap. 2 §; Transportstyrelsen, Redovisningscentraler för taxitrafik.",
    note_fr: "Au moins une fois par semaine. SFS 2012:211, ch. 2 a, art. 4.",
  },
  {
    id: "rs-owner-redovisning-tradlost",
    topic: "agare",
    trackHint: "owner",
    corpus: "owner-seed",
    type: "qcm",
    source: "SFS 2012:211 2 a kap. 3 §",
    freq: "medium",
    sv: "Hur ska taxameteruppgifter överföras till redovisningscentralen? | Alt: A. Med pappersutskrift en gång i månaden | Alt: B. Digitalt och trådlöst | Alt: C. Bara via vanlig post | Alt: D. Bara vid kontrollbesiktning",
    fr: "Comment transmettre les données taximètre ?",
    answer: "B",
    note_sv: "Överföring ska ske digitalt och trådlöst. Källa: SFS 2012:211 2 a kap. 3 §.",
    note_fr: "Numérique et sans fil. SFS 2012:211, ch. 2 a, art. 3.",
  },
  {
    id: "rs-owner-redovisning-obesikt",
    topic: "agare",
    trackHint: "owner",
    corpus: "owner-seed",
    type: "qcm",
    source: "SFS 2012:211 2 a kap. 4 §",
    freq: "medium",
    sv: "Vad ska tillståndshavaren göra om en taxameter inte har brukats under perioden sedan senaste överföringen? | Alt: A. Inget, tystnad räcker | Alt: B. Ge redovisningscentralen besked om detta och om orsaken, senast när uppgifterna skulle ha överförts | Alt: C. Vänta till nästa årliga besiktning | Alt: D. Avregistrera fordonet hos Skatteverket",
    fr: "Taximètre inutilisé : que faire ?",
    answer: "B",
    note_sv: "Tillståndshavaren ska ge redovisningscentralen besked om att taxametern inte brukats och om orsaken, senast vid den tidpunkt då uppgifterna skulle ha överförts. Källa: SFS 2012:211 2 a kap. 4 § andra stycket.",
    note_fr: "Informer la centrale et indiquer le motif. SFS 2012:211, ch. 2 a, art. 4.",
  },
  {
    id: "rs-owner-utan-taxameter-bc",
    topic: "agare",
    trackHint: "owner",
    corpus: "owner-seed",
    type: "qcm",
    source: "SFS 2012:211 2 b kap. 1 §+transportstyrelsen/taxameter",
    freq: "high",
    trap: "Kommunal dispens / frivilligt i glesbygd",
    sv: "Vad krävs om tillståndshavaren bedriver taxitrafik med ett fordon som saknar taxameterutrustning? | Alt: A. Kommunal dispens räcker | Alt: B. Fordonet ska anslutas till en tillståndspliktig beställningscentral och ha särskild utrustning för taxifordon | Alt: C. Inget extra, taxameter är frivillig | Alt: D. Bara en pappersprislista i vindrutan",
    fr: "Sans taximètre : que faut-il ?",
    answer: "B",
    note_sv: "Fordon utan taxameter ska från anmälan för taxitrafik anslutas till en beställningscentral enligt lagen (2014:1020) och ha särskild utrustning för taxifordon. Transportstyrelsen: godkänd taxameter eller särskild utrustning. Källa: SFS 2012:211 2 b kap. 1 §; Transportstyrelsen, Taxameter.",
    note_fr: "Centrale agréée + équipement spécial. SFS 2012:211, ch. 2 b, art. 1.",
  },
  {
    id: "rs-owner-betalning-bc",
    topic: "agare",
    trackHint: "owner",
    corpus: "owner-seed",
    type: "qcm",
    source: "SFS 2012:211 2 b kap. 3–4 §§",
    freq: "medium",
    sv: "Hur ska betalning ske när taxifordonet saknar taxameter och är anslutet till en beställningscentral? | Alt: A. Direkt till föraren eller tillståndshavaren i bilen | Alt: B. Till den beställningscentral som tagit emot beställningen; betalning får inte ske genom förarens eller tillståndshavarens medverkan. Fast pris ska anges innan köruppdraget påbörjas | Alt: C. Valfritt kontant till vem som helst | Alt: D. Bara via Swish till förarens privata nummer",
    fr: "Paiement sans taximètre ?",
    answer: "B",
    note_sv: "Beställningar och betalningar får bara göras till beställningscentralen. Betalningen får inte göras genom förarens eller tillståndshavarens medverkan. Fast pris ska anges innan uppdraget påbörjas. Källa: SFS 2012:211 2 b kap. 3–4 §§.",
    note_fr: "Paiement à la centrale uniquement ; prix fixe avant le départ. SFS 2012:211, ch. 2 b, art. 3–4.",
  },
  {
    id: "rs-owner-anmal-fordon-forst",
    topic: "agare",
    trackHint: "owner",
    corpus: "owner-seed",
    type: "qcm",
    source: "SFS 2012:238 4 kap. 2 §+transportstyrelsen/tillsyn-for-taxitrafiktillstand",
    freq: "high",
    trap: "Köra först, anmäla sen",
    sv: "När ska tillståndshavaren anmäla en personbil eller lätt lastbil som ska användas i taxitrafik? | Alt: A. Inom tre månader efter första körningen | Alt: B. Innan fordonet används i taxitrafik — anmälan ska ha kommit in till Transportstyrelsen | Alt: C. Bara om fordonet är äldre än fem år | Alt: D. Aldrig om fordonet hyrs",
    fr: "Quand déclarer le véhicule ?",
    answer: "B",
    note_sv: "Innan fordonet får användas i taxitrafik ska tillståndshavaren göra en skriftlig anmälan till Transportstyrelsen. Fordonet får inte användas förrän en anmälan som uppfyller kraven har kommit in. Källa: SFS 2012:238 4 kap. 2 §; Transportstyrelsen, Tillsyn av taxitrafiktillstånd.",
    note_fr: "Avant toute utilisation. SFS 2012:238, ch. 4, art. 2.",
  },
  {
    id: "rs-owner-regbesikt-taxi",
    topic: "agare",
    trackHint: "owner",
    corpus: "owner-seed",
    type: "qcm",
    source: "transportstyrelsen/fordon-i-taxitrafik",
    freq: "high",
    sv: "Vilket krav gäller för att du som tillståndshavare ska kunna anmäla ett fordon till taxitrafik? | Alt: A. Fordonet ska vara registreringsbesiktat för taxitrafik | Alt: B. Det räcker att fordonet har vanlig personbilsregistrering | Alt: C. Fordonet måste vara yngre än tre år | Alt: D. Fordonet måste ägas av kommunen",
    fr: "Quelle condition pour déclarer un véhicule ?",
    answer: "A",
    note_sv: "Du kan bara anmäla ett fordon som är registreringsbesiktat för taxitrafik. Vid anmälan kan gula registreringsskyltar beställas och redovisningscentral anges. Källa: Transportstyrelsen, Fordon i taxitrafik.",
    note_fr: "Le véhicule doit avoir passé la réception taxi. Transportstyrelsen, Fordon i taxitrafik.",
  },
  {
    id: "rs-owner-avanmal-gula",
    topic: "agare",
    trackHint: "owner",
    corpus: "owner-seed",
    type: "qcm",
    source: "SFS 2012:238 4 kap. 6 §+transportstyrelsen/fordon-i-taxitrafik",
    freq: "medium",
    sv: "Vad ska tillståndshavaren göra när ett anmält fordon inte längre ska användas i taxitrafik? | Alt: A. Ingenting, skyltarna får sitta kvar | Alt: B. Avanmäla fordonet till Transportstyrelsen innan det tas i bruk för annan trafik, och återlämna de gula registreringsskyltarna | Alt: C. Bara ta bort taxametern | Alt: D. Anmäla till kommunen inom ett år",
    fr: "Fin d'usage taxi : que faire ?",
    answer: "B",
    note_sv: "Tillståndshavaren ska anmäla ändringen till Transportstyrelsen innan fordonet tas i bruk för annan trafik. Gula registreringsskyltar ska återlämnas. Källa: SFS 2012:238 4 kap. 6 §; Transportstyrelsen, Fordon i taxitrafik.",
    note_fr: "Déclarer la sortie et restituer les plaques jaunes.",
  },
  {
    id: "rs-owner-sanktion-fordon-6000",
    topic: "agare",
    trackHint: "owner",
    corpus: "owner-seed",
    type: "qcm",
    source: "transportstyrelsen/tillsyn-for-taxitrafiktillstand",
    freq: "medium",
    sv: "Vilken sanktionsavgift kan påföras den som inte anmäler eller avanmäler fordon i taxitrafik enligt kraven? | Alt: A. 1 000 kronor | Alt: B. 6 000 kronor | Alt: C. 50 000 kronor | Alt: D. Ingen avgift, bara en påminnelse",
    fr: "Quelle amende administrative pour un véhicule non déclaré ?",
    answer: "B",
    note_sv: "Den som inte följer anmälningskravet för fordon ska påföras en sanktionsavgift om 6 000 kronor. Källa: Transportstyrelsen, Tillsyn av taxitrafiktillstånd.",
    note_fr: "6 000 kr. Transportstyrelsen, Tillsyn av taxitrafiktillstånd.",
  },
  {
    id: "rs-owner-sanktion-styrelse-10000",
    topic: "agare",
    trackHint: "owner",
    corpus: "owner-seed",
    type: "qcm",
    source: "transportstyrelsen/tillsyn-for-taxitrafiktillstand+SFS 2012:238 2 kap. 10 §",
    freq: "medium",
    sv: "Vad kan följa om ett aktiebolag inte anmäler ändringar av styrelse eller aktieägare till Transportstyrelsen? | Alt: A. Inget, ändringar anmäls bara till Bolagsverket | Alt: B. Sanktionsavgift på 10 000 kronor | Alt: C. Automatisk återkallelse samma dag | Alt: D. Böter enligt brottsbalken",
    fr: "Changement de conseil non déclaré ?",
    answer: "B",
    note_sv: "I bolagsform ska ändringar av styrelse eller aktieägare anmälas. Om ändringen inte anmäls riskerar företaget sanktionsavgift på 10 000 kronor. Byte av trafikansvarig ska anmälas enligt 2012:238 2 kap. 10 §. Källa: Transportstyrelsen, Tillsyn av taxitrafiktillstånd; SFS 2012:238 2 kap. 10 §.",
    note_fr: "10 000 kr. Transportstyrelsen ; SFS 2012:238, ch. 2, art. 10.",
  },
  {
    id: "rs-owner-aterkallelse-anvands-ej",
    topic: "agare",
    trackHint: "owner",
    corpus: "owner-seed",
    type: "qcm",
    source: "SFS 2012:211 4 kap. 5 §+transportstyrelsen/tillsyn-for-taxitrafiktillstand",
    freq: "high",
    trap: "Tillståndet vilar utan fordon",
    sv: "När ska ett taxitrafiktillstånd återkallas därför att det inte används? | Alt: A. Aldrig, tillståndet vilar utan fordon | Alt: B. Om det inte används och särskilda skäl inte talar emot återkallelse; inget fordon anmält i taxitrafik ses som att tillståndet inte används | Alt: C. Först efter tio år utan körning | Alt: D. Bara om tillståndshavaren begär det",
    fr: "Permis inutilisé : retrait ?",
    answer: "B",
    note_sv: "Tillståndet ska återkallas om det inte används och särskilda skäl inte talar emot. Transportstyrelsen: saknas fordon anmält i taxitrafik ses tillståndet som oanvänt. Källa: SFS 2012:211 4 kap. 5 §; Transportstyrelsen, Tillsyn av taxitrafiktillstånd.",
    note_fr: "Oui, sauf motif particulier ; aucun véhicule déclaré = non-usage.",
  },
  {
    id: "rs-owner-aterkallelse-skatt-overforing",
    topic: "agare",
    trackHint: "owner",
    corpus: "owner-seed",
    type: "qcm",
    source: "SFS 2012:211 4 kap. 2 §+transportstyrelsen/tillsyn-for-taxitrafiktillstand",
    freq: "high",
    sv: "Vilket av följande ska leda till att taxitrafiktillståndet återkallas? | Alt: A. En enstaka parkeringsanmärkning | Alt: B. Väsentligt underlåten betalning av skatter och avgifter, eller upprepad underlåtenhet att överföra taxameteruppgifter | Alt: C. Att föraren byter arbetspass | Alt: D. Att jämförpriset höjs",
    fr: "Quels manquements entraînent le retrait ?",
    answer: "B",
    note_sv: "Tillstånd ska återkallas bland annat vid väsentligt underlåten betalning av skatter och avgifter, upprepad underlåtenhet att överföra taxameteruppgifter, allvarliga brott eller åsidosatta villkor. Källa: SFS 2012:211 4 kap. 2 §; Transportstyrelsen, Tillsyn av taxitrafiktillstånd.",
    note_fr: "Impôts impayés ou défauts répétés de transmission. SFS 2012:211, ch. 4, art. 2.",
  },
  {
    id: "rs-owner-olamplighet-3-5",
    topic: "agare",
    trackHint: "owner",
    corpus: "owner-seed",
    type: "qcm",
    source: "SFS 2012:211 4 kap. 3 §",
    freq: "medium",
    trap: "Sex månader till fem år (det är vid avslag)",
    sv: "Vilken olämplighetstid ska bestämmas när ett taxitrafiktillstånd återkallas på grund av allvarliga missförhållanden eller de omständigheter som anges i 4 kap. 2 §? | Alt: A. Högst tre månader | Alt: B. Lägst tre och högst fem år | Alt: C. Tills vidare utan tidsgräns | Alt: D. Alltid tio år",
    fr: "Durée d'interdiction après retrait ?",
    answer: "B",
    note_sv: "Lägst tre och högst fem år. (Vid avslag på grund av bristande gott anseende är tiden i stället lägst sex månader och högst fem år enligt 2 kap. 12 §.) Källa: SFS 2012:211 4 kap. 3 §.",
    note_fr: "3 à 5 ans. SFS 2012:211, ch. 4, art. 3.",
  },
  {
    id: "rs-owner-varning",
    topic: "agare",
    trackHint: "owner",
    corpus: "owner-seed",
    type: "qcm",
    source: "SFS 2012:211 4 kap. 1 §+transportstyrelsen/tillsyn-for-taxitrafiktillstand",
    freq: "medium",
    sv: "Vad kan Transportstyrelsen besluta i stället för återkallelse om missförhållandena inte är så allvarliga? | Alt: A. Inget, återkallelse är enda påföljden | Alt: B. Varning | Alt: C. Fängelse | Alt: D. Kommunalt näringsförbud",
    fr: "Alternative au retrait ?",
    answer: "B",
    note_sv: "Om missförhållandena inte är så allvarliga att tillståndet bör återkallas får varning meddelas. Varningen registreras i vägtrafikregistret. Källa: SFS 2012:211 4 kap. 1 §; Transportstyrelsen, Tillsyn av taxitrafiktillstånd.",
    note_fr: "Un avertissement. SFS 2012:211, ch. 4, art. 1.",
  },
  {
    id: "rs-owner-anlita-utan-tfl",
    topic: "agare",
    trackHint: "owner",
    corpus: "owner-seed",
    type: "qcm",
    source: "SFS 2012:211 3 kap. 1 § och 5 kap. 4 §",
    freq: "high",
    trap: "Körkort B räcker för anställda",
    sv: "Vad gäller om du som tillståndshavare anlitar en förare som saknar taxiförarlegitimation? | Alt: A. Det är tillåtet om föraren har körkort B | Alt: B. Det är otillåtet; tillståndshavaren kan dömas till böter eller fängelse i högst sex månader | Alt: C. Det är tillåtet under de tre första månaderna | Alt: D. Det är bara föraren som kan straffas",
    fr: "Recruter sans carte professionnelle ?",
    answer: "B",
    note_sv: "Personbil eller lätt lastbil får föras i taxitrafik endast av den som har giltig taxiförarlegitimation (eller tillfällig rätt enligt 2016:145). Tillståndshavare som uppsåtligen eller av oaktsamhet anlitar förare utan sådan behörighet döms till böter eller fängelse i högst sex månader. Källa: SFS 2012:211 3 kap. 1 § och 5 kap. 4 §.",
    note_fr: "Interdit ; amende ou prison ≤ 6 mois. SFS 2012:211, ch. 3 art. 1 et ch. 5 art. 4.",
  },
  {
    id: "rs-owner-olaga-taxitrafik",
    topic: "agare",
    trackHint: "owner",
    corpus: "owner-seed",
    type: "qcm",
    source: "SFS 2012:211 5 kap. 1 §",
    freq: "medium",
    sv: "Vad kan den dömas till som uppsåtligen bedriver taxitrafik utan tillstånd? | Alt: A. Bara erinran | Alt: B. Böter eller fängelse i högst ett år för olaga taxitrafik | Alt: C. Alltid fängelse i lägst två år | Alt: D. Bara återkallelse av körkort",
    fr: "Sanction de l'exploitation sans permis ?",
    answer: "B",
    note_sv: "Olaga taxitrafik: böter eller fängelse i högst ett år. En tillståndshavare som bryter mot villkor i tillståndet döms till böter. Källa: SFS 2012:211 5 kap. 1 §.",
    note_fr: "Amende ou prison ≤ 1 an. SFS 2012:211, ch. 5, art. 1.",
  },
  {
    id: "rs-owner-taxameter-plomb-besikt",
    topic: "agare",
    trackHint: "owner",
    corpus: "owner-seed",
    type: "qcm",
    source: "SFS 2012:238 5 kap. 1 och 3 §§+transportstyrelsen/taxameter",
    freq: "high",
    trap: "Besiktning vartannat år",
    sv: "Vad ansvarar tillståndshavaren för när fordonet har taxameter? | Alt: A. Att taxametern är av godkänd typ, fungerar, är kontrollerad och plomberad samt besiktas senast ett år efter installation eller senaste besiktning | Alt: B. Att taxametern besiktas vartannat år tillsammans med fordonet | Alt: C. Inget, bara föraren ansvarar | Alt: D. Att taxametern byts ut varje månad",
    fr: "Devoirs de l'exploitant sur le taximètre ?",
    answer: "A",
    note_sv: "Fordon får användas i taxitrafik bara med godkänd, fungerande, kontrollerad och plomberad taxameterutrustning (eller särskild utrustning enligt 2 b kap.). Besiktning senast ett år från installation eller senaste besiktning; kontrollrapport ska upprättas. Källa: SFS 2012:238 5 kap. 1 och 3 §§; Transportstyrelsen, Taxameter.",
    note_fr: "Type agréé, plombé, contrôlé au plus tard tous les ans. SFS 2012:238, ch. 5, art. 1 et 3.",
  },
  {
    id: "rs-owner-taxameter-varje-uppdrag",
    topic: "agare",
    trackHint: "owner",
    corpus: "owner-seed",
    type: "qcm",
    source: "transportstyrelsen/taxameter",
    freq: "high",
    sv: "Som tillståndshavare, när ska taxametern användas i ett fordon som är utrustat med taxameter? | Alt: A. Bara vid kontantbetalning | Alt: B. Vid varje köruppdrag | Alt: C. Bara om kunden begär kvitto | Alt: D. Bara utanför tätort",
    fr: "Quand l'exploitant doit-il exiger l'usage du taximètre ?",
    answer: "B",
    note_sv: "Om fordonet är utrustat med taxameter ska den användas vid varje köruppdrag. Det är tillståndshavarens ansvar att verksamheten följer detta. Källa: Transportstyrelsen, Taxameter.",
    note_fr: "À chaque course. Transportstyrelsen, Taxameter.",
  },
  {
    id: "rs-owner-kvitto-erbjuda",
    topic: "agare",
    trackHint: "owner",
    corpus: "owner-seed",
    type: "qcm",
    source: "TSFS 2013:41 5 kap. 1 §+transportstyrelsen/prisinformation",
    freq: "medium",
    sv: "Vad ska erbjudas kunden efter varje avslutat köruppdrag när taxameter används? | Alt: A. Inget, kvitto bara på begäran | Alt: B. Kvitto från taxameterutrustningen, eller följesedel om beloppet ska faktureras | Alt: C. Bara muntligt pris | Alt: D. Bara jämförprisdekalen",
    fr: "Quel justificatif après la course ?",
    answer: "B",
    note_sv: "Efter varje avslutat köruppdrag ska kunden erbjudas kvitto, eller följesedel vid faktura, i papper eller elektronisk form som kunden kan ta emot. Kvittot ska visa körd sträcka och tid. Källa: TSFS 2013:41 5 kap. 1 §; Transportstyrelsen, Prisinformation för taxiföretag.",
    note_fr: "Reçu taximètre ou bordereau. TSFS 2013:41, ch. 5, art. 1.",
  },
  {
    id: "rs-owner-trafikforsakring-skylt",
    topic: "agare",
    trackHint: "owner",
    corpus: "owner-seed",
    type: "qcm",
    source: "SFS 2012:211 5 kap. 8 §",
    freq: "high",
    sv: "När får en polisman eller bilinspektör ta hand om den särskilda registreringsskylten för ett taxifordon? | Alt: A. Aldrig, skylten är privat egendom | Alt: B. Bland annat om fordonet saknar föreskriven trafikförsäkring eller om taxameterutrustningen inte uppfyller kraven | Alt: C. Bara om fordonet är äldre än tio år | Alt: D. Bara på tillståndshavarens begäran",
    fr: "Quand peut-on retirer les plaques taxi ?",
    answer: "B",
    note_sv: "Särskild taxiskylt får tas om hand bland annat om fordonet saknar föreskriven trafikförsäkring, om taxameterutrustningen inte uppfyller kraven, vid körförbud, användningsförbud eller olaga användning. Källa: SFS 2012:211 5 kap. 8 §.",
    note_fr: "Sans assurance obligatoire ou taximètre non conforme, entre autres. SFS 2012:211, ch. 5, art. 8.",
  },
  {
    id: "rs-owner-ag-tidbok-kostnadsfritt",
    topic: "agare",
    trackHint: "owner",
    corpus: "owner-seed",
    type: "qcm",
    source: "SFS 1994:1297 9 §+transportstyrelsen/vilotider-latta-fordon",
    freq: "high",
    trap: "Föraren köper tidboken själv",
    sv: "Vad är arbetsgivarens skyldighet när anställda taxiförare omfattas av vilotidsreglerna? | Alt: A. Föraren ska själv köpa tidbok | Alt: B. Arbetsgivaren ska utan kostnad tillhandahålla varje förare en tidbok och se till att de föreskrivna anteckningarna görs | Alt: C. Bara beställningscentralen ansvarar | Alt: D. Tidbok krävs inte för anställda",
    fr: "Devoir de l'employeur concernant le tidbok ?",
    answer: "B",
    note_sv: "Arbetsgivaren ska utan kostnad tillhandahålla tidbok och se till att föreskrivna anteckningar görs. Transportstyrelsen: ge tidböcker med företagets uppgifter, anteckna utlämning och återlämning, föra förteckning och visa upp på begäran. Källa: SFS 1994:1297 9 §; Transportstyrelsen, Vilotider för lätta fordon.",
    note_fr: "Fournir le tidbok gratuitement et veiller aux mentions. SFS 1994:1297, art. 9.",
  },
  {
    id: "rs-owner-ag-bevara-12",
    topic: "agare",
    trackHint: "owner",
    corpus: "owner-seed",
    type: "qcm",
    source: "SFS 1994:1297 8 §+transportstyrelsen/vilotider-latta-fordon",
    freq: "high",
    trap: "En vecka / tre månader",
    sv: "Hur länge ska arbetsgivaren bevara anteckningarna om dygnsvila för varje anställd förare? | Alt: A. En vecka | Alt: B. Tre månader | Alt: C. Minst tolv månader från den dag anteckningarna gäller | Alt: D. Sju år",
    fr: "Durée de conservation des notes de repos ?",
    answer: "C",
    note_sv: "Arbetsgivaren ska bevara anteckningarna under minst tolv månader från den dag de gäller. Detsamma gäller egenföretagare. Källa: SFS 1994:1297 8 §; Transportstyrelsen, Vilotider för lätta fordon.",
    note_fr: "Au moins douze mois. SFS 1994:1297, art. 8.",
  },
  {
    id: "rs-owner-ag-anteckna-sjalv",
    topic: "agare",
    trackHint: "owner",
    corpus: "owner-seed",
    type: "qcm",
    source: "SFS 1994:1297 5 §",
    freq: "medium",
    sv: "Vem ska, utöver föraren, upprätta anteckningar om dygnsvila när föraren är anställd? | Alt: A. Bara föraren | Alt: B. Motsvarande anteckningar ska även upprättas hos arbetsgivaren | Alt: C. Bara Skatteverket | Alt: D. Bara beställningscentralen",
    fr: "L'employeur doit-il aussi noter le repos ?",
    answer: "B",
    note_sv: "Föraren antecknar i tidboken innan körningen påbörjas. Är föraren anställd ska motsvarande anteckningar även upprättas hos arbetsgivaren. Källa: SFS 1994:1297 5 §.",
    note_fr: "Oui, des notes correspondantes chez l'employeur. SFS 1994:1297, art. 5.",
  },
  {
    id: "rs-owner-tillsyn-ts",
    topic: "agare",
    trackHint: "owner",
    corpus: "owner-seed",
    type: "qcm",
    source: "SFS 2012:238 4 kap. 1 §+SFS 2012:211 4 kap. 16 §",
    freq: "medium",
    sv: "Vilken myndighet utövar tillsyn över att tillståndshavare följer taxitrafiklagen? | Alt: A. Kommunen | Alt: B. Transportstyrelsen | Alt: C. Trafikverket | Alt: D. Svenska Taxiförbundet",
    fr: "Qui contrôle les exploitants ?",
    answer: "B",
    note_sv: "Transportstyrelsen är tillsynsmyndighet och utövar tillsyn över att tillståndshavare bedriver verksamheten enligt lagen. Källa: SFS 2012:211 4 kap. 16 §; SFS 2012:238 4 kap. 1 §.",
    note_fr: "Transportstyrelsen. SFS 2012:211, ch. 4, art. 16.",
  },
];
